#!/bin/bash

# Prerequisite.
[ -f "$0" ] || { echo -e "\e[91m" "Cannot run as dot command. Hit Control+c now." "\e[39m"; read; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --fast) fast=1; shift ;;
        --root-sure) root_sure=1; shift ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Command.
command="$1"; shift
if [ -n "$command" ];then
    if [[ ! "$command" =~ ^gpl-.*\.sh ]];then
        echo -e "\e[91m" "Command ${command} is unknown." "\e[39m"; exit 1
    fi
else
    command=list
fi

# Functions.
[[ $(type -t GplWrapper_printVersion) == function ]] || GplWrapper_printVersion() {
    echo '0.1.0'
}
[[ $(type -t GplWrapper_printHelp) == function ]] || GplWrapper_printHelp() {
    cat << EOF
GPL Wrapper
Variation Default
Version `GplWrapper_printVersion`

EOF
    cat << 'EOF'
Usage: gpl-wrapper.sh [file]

Options:

Global Options:
   --fast
        No delay every subtask.
   --version
        Print version of this script.
   --help
        Show this help.
   --root-sure
        Bypass root checking.

Environment Variables:
   BINARY_DIRECTORY
        Default to $HOME/bin

Dependency:
   gpl-dependency-manager.sh
EOF
}

# Help and Version.
[ -n "$help" ] && { GplWrapper_printHelp; exit 1; }
[ -n "$version" ] && { GplWrapper_printVersion; exit 1; }

# Dependency.
while IFS= read -r line; do
    command -v "${line}" >/dev/null || { echo -e "\e[91m""Unable to proceed, ${line} command not found." "\e[39m"; exit 1; }
done <<< `GplWrapper_printHelp | sed -n '/^Dependency:/,$p' | sed -n '2,/^$/p' | sed 's/^ *//g'`

# Common Functions.
[[ $(type -t red) == function ]] || red() { echo -ne "\e[91m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
[[ $(type -t green) == function ]] || green() { echo -ne "\e[92m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
[[ $(type -t yellow) == function ]] || yellow() { echo -ne "\e[93m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
[[ $(type -t blue) == function ]] || blue() { echo -ne "\e[94m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
[[ $(type -t magenta) == function ]] || magenta() { echo -ne "\e[95m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
[[ $(type -t error) == function ]] || error() { echo -n "$INDENT" >&2; red "$@" >&2; echo >&2; }
[[ $(type -t success) == function ]] || success() { echo -n "$INDENT" >&2; green "$@" >&2; echo >&2; }
[[ $(type -t chapter) == function ]] || chapter() { echo -n "$INDENT" >&2; yellow "$@" >&2; echo >&2; }
[[ $(type -t title) == function ]] || title() { echo -n "$INDENT" >&2; blue "$@" >&2; echo >&2; }
[[ $(type -t code) == function ]] || code() { echo -n "$INDENT" >&2; magenta "$@" >&2; echo >&2; }
[[ $(type -t x) == function ]] || x() { echo >&2; exit 1; }
[[ $(type -t e) == function ]] || e() { echo -n "$INDENT" >&2; echo "$@" >&2; }
[[ $(type -t _) == function ]] || _() { echo -n "$INDENT" >&2; echo -n "$@" >&2; }
[[ $(type -t _,) == function ]] || _,() { echo -n "$@" >&2; }
[[ $(type -t _.) == function ]] || _.() { echo >&2; }
[[ $(type -t __) == function ]] || __() { echo -n "$INDENT" >&2; echo -n '    ' >&2; [ -n "$1" ] && echo "$@" >&2 || echo -n  >&2; }
[[ $(type -t ____) == function ]] || ____() { echo >&2; [ -n "$delay" ] && sleep "$delay"; }

# Functions.
[[ $(type -t GplWrapper_GplPromptOptions) == function ]] || GplWrapper_GplPromptOptions() {
    command="$1"
    argument_pass=()
    options=`$command --help | sed -n '/^Options[:\.]$/,$p' | sed -n '2,/^$/p'`
    if [ -n "$options" ];then
        chapter Prepare argument for command '`'$command'`'.
        until [[ -z "$options" ]];do
            parameter=`sed -n 1p <<< "$options" | xargs`
            is_required=
            is_flag=
            value_addon=
            is_flagvalue=
            if [[ "${parameter:(-1):1}" == '*' ]];then
                is_required=1
                parameter="${parameter::-1}"
                parameter=`xargs <<< "$parameter"`
            elif [[ "${parameter:(-1):1}" == '^' ]];then
                is_flag=1
                parameter="${parameter::-1}"
                parameter=`xargs <<< "$parameter"`
            fi
            label=`sed -n 2p <<< "$options" | xargs`
            if grep -q -i -E '(^|\.\s)Multivalue\.' <<< "$label";then
                value_addon=multivalue
            fi
            if grep -q -i -E '(^|\.\s)Can have value\.' <<< "$label";then
                value_addon=canhavevalue
            fi
            options=`sed -n '3,$p' <<< "$options"`
            if [ -n "$is_required" ];then
                _ 'Argument '; magenta ${parameter};_, ' is '; yellow required; _, ". ${label}"; _.
                value=
                until [[ -n "$value" ]];do
                    read -p "Type the value: " value
                done
                argument_pass+=("${parameter}=${value}")
            elif [ -n "$is_flag" ];then
                _ 'Argument '; magenta ${parameter};_, ' is '; _, optional; _, ". ${label}"; _.
                read -p "Add this argument [yN]? " value
                until [[ "$value" =~ ^[yYnN]*$ ]]; do
                    echo "$value: invalid selection."
                    read -p "Add this argument [yN]? " value
                done
                if [[ "$value" =~ ^[yY]$ ]]; then
                    if [[ "$value_addon" == 'canhavevalue' ]];then
                        read -p "Do you want fill with value [yN]? " value
                        until [[ "$value" =~ ^[yYnN]*$ ]]; do
                            echo "$value: invalid selection."
                            read -p "Do you want fill with value [yN]? " value
                        done
                        if [[ "$value" =~ ^[yY]$ ]]; then
                            read -p "Type the value: " value
                            argument_pass+=("${parameter}=${value}")
                        else
                            argument_pass+=("${parameter}")
                        fi
                    else
                        argument_pass+=("${parameter}")
                    fi
                fi
            else
                _ 'Argument '; magenta ${parameter};_, ' is '; _, optional; _, ". ${label}"; _.
                read -p "Type the value: " value
                if [ -n "$value" ];then
                    argument_pass+=("${parameter}=${value}")
                fi
            fi
            if [[ "$value_addon" == 'multivalue' ]];then
                again=1
                until [ -z "$again" ]; do
                    if [ -n "$is_flag" ];then
                        read -p "Add this argument again [yN]? " value
                    else
                        read -p "Add other value [yN]? " value
                    fi
                    until [[ "$value" =~ ^[yYnN]*$ ]]; do
                        echo "$value: invalid selection."
                        if [ -n "$is_flag" ];then
                            read -p "Add this argument again [yN]? " value
                        else
                            read -p "Add other value [yN]? " value
                        fi
                    done
                    if [[ "$value" =~ ^[yY]$ ]]; then
                        if [ -n "$is_flag" ];then
                            argument_pass+=("${parameter}")
                        else
                            read -p "Type the value: " value
                            [ -n "$value" ] && argument_pass+=("${parameter}=${value}")
                        fi
                    else
                        again=
                    fi
                done
            fi
        done
        ____
    fi
}

if [ $command == list ];then
    cat << 'EOF'
gpl-amavis-setup-ispconfig.sh
gpl-certbot-autoinstaller.sh
gpl-certbot-digitalocean-autoinstaller.sh
gpl-certbot-setup-nginx.sh
gpl-composer-autoinstaller.sh
gpl-debian-11-setup-basic.sh
gpl-digitalocean-api-manage-domain-record.sh
gpl-digitalocean-api-manage-domain.sh
gpl-drupal-autoinstaller-nginx-php-fpm.sh
gpl-drupal-setup-drush-alias.sh
gpl-drupal-setup-dump-variables.sh
gpl-drupal-setup-variation1.sh
gpl-drupal-setup-variation2.sh
gpl-drupal-setup-variation3.sh
gpl-drupal-setup-wrapper-nginx-setup-drupal.sh
gpl-ispconfig-autoinstaller-nginx-php-fpm.sh
gpl-ispconfig-control-manage-domain.sh
gpl-ispconfig-control-manage-email-alias.sh
gpl-ispconfig-control-manage-email-mailbox.sh
gpl-ispconfig-setup-dump-variables.sh
gpl-ispconfig-setup-internal-command.sh
gpl-ispconfig-setup-variation1.sh
gpl-ispconfig-setup-variation2.sh
gpl-ispconfig-setup-wrapper-certbot-setup-nginx.sh
gpl-ispconfig-setup-wrapper-digitalocean.sh
gpl-ispconfig-setup-wrapper-nginx-setup-php-fpm.sh
gpl-mariadb-autoinstaller.sh
gpl-mariadb-setup-database.sh
gpl-mariadb-setup-ispconfig.sh
gpl-nginx-autoinstaller.sh
gpl-nginx-setup-drupal.sh
gpl-nginx-setup-hello-world-static.sh
gpl-nginx-setup-ispconfig.sh
gpl-nginx-setup-php-fpm.sh
gpl-nginx-setup-static.sh
gpl-php-autoinstaller.sh
gpl-php-setup-adjust-cli-version.sh
gpl-php-setup-drupal.sh
gpl-php-setup-ispconfig.sh
gpl-phpmyadmin-autoinstaller-nginx-php-fpm.sh
gpl-postfix-autoinstaller.sh
gpl-postfix-setup-ispconfig.sh
gpl-roundcube-autoinstaller-nginx-php-fpm.sh
gpl-roundcube-setup-ispconfig-integration.sh
gpl-ubuntu-22.04-setup-basic.sh
gpl-wsl-setup-lemp-stack.sh
EOF
    ____

    read -p "Type the command to execute: " command
    ____

    if [ -z "$command" ];then
        exit
    fi

fi

if [ -z "$fast" ];then
    seconds=2
    start="$(($(date +%s) + $seconds))"
    yellow It is highly recommended that you use; _, ' ' ; magenta --fast; _, ' ' ; yellow option.; _.
    while [ "$start" -ge `date +%s` ]; do
        time="$(( $start - `date +%s` ))"
        yellow .
        sleep .8
    done
    _.
    ____
fi

# Title.
title GPL Wrapper
_ 'Variation '; yellow Default; _.
_ 'Version '; yellow `GplWrapper_printVersion`; _.
____

# Requirement, validate, and populate value.
chapter Dump variable.
delay=.5; [ -n "$fast" ] && unset delay
BINARY_DIRECTORY=${BINARY_DIRECTORY:=$HOME/bin}
code 'BINARY_DIRECTORY="'$BINARY_DIRECTORY'"'
____

if [ -z "$root_sure" ];then
    chapter Mengecek akses root.
    if [[ "$EUID" -ne 0 ]]; then
        error This script needs to be run with superuser privileges.; x
    else
        __ Privileges.; root_sure=1
    fi
    ____
fi

chapter Execute:
[ -n "$fast" ] && isfast='--fast ' || isfast=''
code gpl-dependency-manager.sh ${isfast}$command
____

_ -----------------------------------------------------------------------;_.;_.;
command -v "gpl-dependency-manager.sh" >/dev/null || { red "Unable to proceed, gpl-dependency-manager.sh command not found." "\e[39m"; x; }
BINARY_DIRECTORY="$BINARY_DIRECTORY" INDENT="    " gpl-dependency-manager.sh $command $isfast --root-sure --binary-directory-exists-sure
_ -----------------------------------------------------------------------;_.;_.;

PATH="${BINARY_DIRECTORY}:${PATH}"
GplWrapper_GplPromptOptions $command
if [[ "${#argument_pass[@]}" -gt 0 ]];then
    set -- "${argument_pass[@]}"
    unset argument_pass
fi

chapter Execute:
[ -n "$fast" ] && isfast='--fast ' || isfast=''
code $command ${isfast}"$@"
____

if [ -z "$fast" ];then
    seconds=2
    start="$(($(date +%s) + $seconds))"
    yellow It is highly recommended that you use; _, ' ' ; magenta --fast; _, ' ' ; yellow option.; _.
    while [ "$start" -ge `date +%s` ]; do
        time="$(( $start - `date +%s` ))"
        yellow .
        sleep .8
    done
    _.
    ____
fi

chapter Timer Start.
e Begin: $(date +%Y%m%d-%H%M%S)
GplWrapper_BEGIN=$SECONDS
____

_ -----------------------------------------------------------------------;_.;_.;
command -v "$command" >/dev/null || { red "Unable to proceed, $command command not found."; x; }
INDENT="    " $command $isfast --root-sure "$@"
_ -----------------------------------------------------------------------;_.;_.;

chapter Timer Finish.
e End: $(date +%Y%m%d-%H%M%S)
GplWrapper_END=$SECONDS
duration=$(( GplWrapper_END - GplWrapper_BEGIN ))
hours=$((duration / 3600)); minutes=$(( (duration % 3600) / 60 )); seconds=$(( (duration % 3600) % 60 ));
runtime=`printf "%02d:%02d:%02d" $hours $minutes $seconds`
_ Duration: $runtime; if [ $duration -gt 60 ];then _, " (${duration} seconds)"; fi; _, '.'; _.
____

# parse-options.sh \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --fast
# --version
# --help
# --root-sure
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
