<?php

/**
 * @file
 * Contains gpl.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gpl_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gpl module.
    case 'help.page.gpl':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Cara cepat bikin system gak pake lama berbasis file configurasi YML.') . '</p>';
      return $output;

    default:
  }
}
